Q1:Create a dataset as follow in the table.

In [ ]:
import pandas as pd
data = {
'Tid': [1,2,3,4,5,6,7,8,9,10],
'Refund': ['YES','NO','NO','YES','NO','NO','YES','NO','NO','NO'],
'Marital Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
'Taxable Income':[125000,100000,70000,120000,95000,60000,220000,85000,75000,90000],
'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}
df=pd.DataFrame(data)
print(df)

   Tid Refund Marital Status  Taxable Income Cheat
0    1    YES         Single          125000    No
1    2     NO        Married          100000    No
2    3     NO         Single           70000    No
3    4    YES        Married          120000    No
4    5     NO       Divorced           95000   Yes
5    6     NO        Married           60000    No
6    7    YES       Divorced          220000    No
7    8     NO         Single           85000   Yes
8    9     NO        Married           75000    No
9   10     NO         Single           90000   Yes

Q2:From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [ ]:
df=pd.DataFrame(data)
print(df.iloc[[0,4,7,8]])

   Tid Refund Marital Status  Taxable Income Cheat
0    1    YES         Single          125000    No
4    5     NO       Divorced           95000   Yes
7    8     NO         Single           85000   Yes
8    9     NO        Married           75000    No

Q3.1:Select row from index 3 to 7.

In [ ]:
df=pd.DataFrame(data)
print(df.iloc[3:8])

   Tid Refund Marital Status  Taxable Income Cheat
3    4    YES        Married          120000    No
4    5     NO       Divorced           95000   Yes
5    6     NO        Married           60000    No
6    7    YES       Divorced          220000    No
7    8     NO         Single           85000   Yes

Q3.2:Select row from index 4 to 8, and column 2 to 4.

In [ ]:
print(df.iloc[4:9, 2:5])

  Marital Status  Taxable Income Cheat
4       Divorced           95000   Yes
5        Married           60000    No
6       Divorced          220000    No
7         Single           85000   Yes
8        Married           75000    No

Q3.3:Select all rows with column index 1 to 3 (include index 3 during selection).

In [ ]:
print(df.iloc[0:,1:3])

  Refund Marital Status
0    YES         Single
1     NO        Married
2     NO         Single
3    YES        Married
4     NO       Divorced
5     NO        Married
6    YES       Divorced
7     NO         Single
8     NO        Married
9     NO         Single

Q4:Read a csv file and display its first five rows.
Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
iris = pd.read_csv('/content/drive/My Drive/Iris.csv')
print(iris.head())
iris.drop(4, axis=0, inplace=True)
iris.drop(iris.columns[3], axis=1, inplace=True)
print(iris.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [ ]:
import pandas as pd

employee_data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "FirstName": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT","Marketing","Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [75000, 85000, 70000, 65000, 60000],
    "YearsOfExperience": [4, 8, 10, 3, 12],
    "JoiningDate": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "male", "male", "Female", "male"],
    "Bonus": [4.5, 4.0, 3.8, 4.7, 3.5]
}
df = pd.DataFrame(employee_data)

df.to_csv("employees.csv", index=False)

print("employees.csv file has been created")
df.head()

employees.csv file has been created

,EmployeeID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus
0,101,Alice,HR,29,75000,4,2020-03-15,Female,4.5
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8
3,104,Diana,Marketing,28,65000,3,2021-02-10,Female,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5

Q6:Create a sample dataset (employees.csv) containing information about employees in
a company.
Employee_ID Name Department Age Salary Years_of_Experience Joining_Date Gender Bonus Rating

a) Shape (number of rows and columns) of the DataFrame.

b) Summary of the DataFrame that includes the data types and non-null counts for
each column.

c) Generate descriptive statistics.

d) Display the first 5 rows and last 3 rows of the dataset.

e) Calculate the following statistics from the dataset:

i. The average salary of employees.

ii. The total bonus paid to all employees.

iii. The youngest employee's age.

iv. The highest performance rating.

f) Sort the DataFrame by the Salary column in descending order.

g) Add a new column that categorizes employees based on their performance rating:

i. Excellent for ratings >= 4.5

ii. Good for ratings >= 4.0 but < 4.5

iii. Average for ratings < 4.0

h) Identify missing values in the DataFrame.

i) Rename the Employee_ID column to ID.

j) Find all employees who:

i. Have more than 5 years of experience.

ii. Belong to the IT department.

k) Modify the dataset by adding a new column, Tax, which deducts 10% of the
Salary.

l) Save the modified DataFrame (with added columns) to a new CSV file.

In [ ]:
shape = df.shape
print(f"The shape of the DataFrame is: {shape}")
print(f"Number of rows: {shape[0]}")
print(f"Number of columns: {shape[1]}")

The shape of the DataFrame is: (5, 9)
Number of rows: 5
Number of columns: 9

In [ ]:
print("\nSummary of the DataFrame:")
print(df.info())

print("\nDescriptive statistics of the DataFrame:")
print(df.describe())

Summary of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         5 non-null      int64
 1   FirstName          5 non-null      object
 2   Department         5 non-null      object
 3   Age                5 non-null      int64
 4   Salary             5 non-null      int64
 5   YearsOfExperience  5 non-null      int64
 6   JoiningDate        5 non-null      object
 7   Gender             5 non-null      object
 8   Bonus              5 non-null      float64
dtypes: float64(1), int64(4), object(4)
memory usage: 492.0+ bytes
None

Descriptive statistics of the DataFrame:
       EmployeeID        Age        Salary  YearsOfExperience     Bonus
count    5.000000   5.000000      5.000000           5.000000  5.000000
mean   103.000000  34.000000  71000.000000           7.400000  4.100000
std      1.581139   5.612486   9617.692031           3.847077  0.494975
min    101.000000  28.000000  60000.000000           3.000000  3.500000
25%    102.000000  29.000000  65000.000000           4.000000  3.800000
50%    103.000000  34.000000  70000.000000           8.000000  4.000000
75%    104.000000  38.000000  75000.000000          10.000000  4.500000
max    105.000000  41.000000  85000.000000          12.000000  4.700000

In [ ]:
print("First 5 rows of the DataFrame:")
print(df.head())
print("\nLast 3 rows of the DataFrame:")
print(df.tail(3))

First 5 rows of the DataFrame:
   EmployeeID FirstName Department  Age  Salary  YearsOfExperience  \
0         101     Alice         HR   29   75000                  4
1         102       Bob         IT   34   85000                  8
2         103   Charlie         IT   41   70000                 10
3         104     Diana  Marketing   28   65000                  3
4         105    Edward      Sales   38   60000                 12

  JoiningDate  Gender  Bonus
0  2020-03-15  Female    4.5
1  2017-07-19    male    4.0
2  2013-06-01    male    3.8
3  2021-02-10  Female    4.7
4  2010-11-25    male    3.5

Last 3 rows of the DataFrame:
   EmployeeID FirstName Department  Age  Salary  YearsOfExperience  \
2         103   Charlie         IT   41   70000                 10
3         104     Diana  Marketing   28   65000                  3
4         105    Edward      Sales   38   60000                 12

  JoiningDate  Gender  Bonus
2  2013-06-01    male    3.8
3  2021-02-10  Female    4.7
4  2010-11-25    male    3.5

In [ ]:
average_salary = df['Salary'].mean()
print(f"The average salary of employees is: {average_salary}")

total_bonus = df['Bonus'].sum()
print(f"The total bonus paid to all employees is: {total_bonus}")

youngest_age = df['Age'].min()
print(f"The youngest employee's age is: {youngest_age}")

highest_bonus = df['Bonus'].max()
print(f"The highest performance rating (represented by Bonus) is: {highest_bonus}")

The average salary of employees is: 71000.0
The total bonus paid to all employees is: 20.5
The youngest employee's age is: 28
The highest performance rating (represented by Bonus) is: 4.7

In [ ]:
df_sorted = df.sort_values(by='Salary', ascending=False)
df_sorted

,EmployeeID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0
0,101,Alice,HR,29,75000,4,2020-03-15,Female,4.5
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8
3,104,Diana,Marketing,28,65000,3,2021-02-10,Female,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5

In [ ]:
def categorize_performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df['PerformanceCategory'] = df['Bonus'].apply(categorize_performance)
df

,EmployeeID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus,PerformanceCategory
0,101,Alice,HR,29,75000,4,2020-03-15,Female,4.5,Excellent
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0,Good
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8,Average
3,104,Diana,Marketing,28,65000,3,2021-02-10,Female,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5,Average

In [ ]:
missing_values = df.isnull().sum()
print("\nMissing values per column using isnull():\n", missing_values)

Missing values per column using isnull():
 EmployeeID             0
FirstName              0
Department             0
Age                    0
Salary                 0
YearsOfExperience      0
JoiningDate            0
Gender                 0
Bonus                  0
PerformanceCategory    0
dtype: int64

In [ ]:
df = df.rename(columns={"EmployeeID": "ID"})
df.to_csv("employees.csv", index=False)
df

,ID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus,PerformanceCategory
0,101,Alice,HR,29,75000,4,2020-03-15,Female,4.5,Excellent
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0,Good
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8,Average
3,104,Diana,Marketing,28,65000,3,2021-02-10,Female,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5,Average

In [ ]:
experienced_employees = df[df['YearsOfExperience'] > 5]
experienced_employees

,ID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus,PerformanceCategory
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0,Good
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5,Average

In [ ]:
IT_department= df[df['Department'] == 'IT']
IT_department

,ID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus,PerformanceCategory
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0,Good
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8,Average

In [ ]:
df['Tax'] = df['Salary'] * 0.10
df

,ID,FirstName,Department,Age,Salary,YearsOfExperience,JoiningDate,Gender,Bonus,PerformanceCategory,Tax
0,101,Alice,HR,29,75000,4,2020-03-15,Female,4.5,Excellent,7500.0
1,102,Bob,IT,34,85000,8,2017-07-19,male,4.0,Good,8500.0
2,103,Charlie,IT,41,70000,10,2013-06-01,male,3.8,Average,7000.0
3,104,Diana,Marketing,28,65000,3,2021-02-10,Female,4.7,Excellent,6500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,male,3.5,Average,6000.0

In [ ]:
df.to_csv("new_employees.csv", index=False)
print("DataFrame saved to new file")

DataFrame saved to new file